from discover_bare_metal import DiscoverMetal
from create_instance import ProvisionServer
from resize_instance import ResizeInstance
from update_instance import UpdateInstance

assert DiscoverMetal
assert ProvisionServer
assert UpdateInstance
assert ResizeInstance
